### ISSUE TITLE
README.md파일 내용

### ISSUE THREAD

**Issue by apple0605a** [teamProjectMini/teamProject#1]

**Comment by apple0605a** [comment]
README

**Comment by 22100522LeeSuin** [comment]
- mini project 주제: 가계부 프로그램
- mini project 에 대한 소개: 지출이 많은 대학생들에게 도움이 되는 돈 관리 프로그램

**Comment by 22100522LeeSuin** [comment]
저희 이미지는 어떤 이미지를 사용하는게 좋을까요?

**Comment by apple0605a** [comment]
이거 어떤가요?
https://cdn.pixabay.com/photo/2015/02/02/11/09/office-620822_960_720.jpg

**Comment by apple0605a** [comment]
프로젝트 포함 시킬 기능은
CRUD
FILE 저장 및 수정

그리고 여기에 아까 말씀하신
분야별 지출 내역 조회
총 지출 계산 조회

일단 이정도 생각하면 될까요?

**Comment by 22100522LeeSuin** [comment]
사진 좋은 것 같아요! 더 좋은 사진 발견하면 말씀드리겠습니다! 
네!

**Comment by apple0605a** [comment]
README파일 지금 수정하고 계신가요?

**Comment by 22100522LeeSuin** [comment]
README 파일 팀 파일을 수정하는 건가요?

**Comment by apple0605a** [comment]
네 그런 것 같아요

**Comment by 22100522LeeSuin** [comment]
보니까 각자 README파일에 작성이라고 나와있는데 개인 repo 안에 README 파일에 작성해서 URL을 올리는 걸까요?

**Comment by apple0605a** [comment]
그게 맞는 것 같아요

**Comment by 22100522LeeSuin** [comment]
네네! 저희 개발환경 및 언어는 C프로그래밍이라고 적으면 될까요.?

**Comment by apple0605a** [comment]
저는 작성 부분을 나눠서 팀 README 파일에 각자 부분을 작성하라는 걸로 이해했었어요

**Comment by apple0605a** [comment]
네 언어는 C라고 그냥 적으시면 될 것 같아요

**Comment by 22100522LeeSuin** [comment]
아하 그러면 일단 팀 README 파일에 수정을 하고 혹시 모르니까 각자 README파일에도 추가를 해놓는 건 어떨까요?

**Comment by apple0605a** [comment]
네 그렇게 하는게 좋을 것 같아요

**Comment by 22100522LeeSuin** [comment]
그러면 저희 역할분배를 어떻게 할까요?

**Comment by 22100522LeeSuin** [comment]
- mini project 주제: 가계부 프로그램
- mini project 에 대한 소개: 지출이 많은 대학생들에게 도움이 되는 돈 관리 프로그램
- image(pixabay 등 무료 이미지 활용): https://cdn.pixabay.com/photo/2015/02/02/11/09/office-620822_960_720.jpg
- project 에 포함시킬 기능 설명(향후 변경 가능함)
CRUD
FILE 저장 및 수정
분야별 지출 내역 조회
총 지출 계산 조회
향후 변경 및 추가 예정
- 개발환경 및 언어: C프로그래밍 언어
- 팀소개 및 팀원이 맡은 역할:

**Comment by apple0605a** [comment]
그러게요....

**Comment by apple0605a** [comment]
혹시 원하시는 역할이 있으신가요?

**Comment by 22100522LeeSuin** [comment]
흠 제가 파일 저장 및 조회를 한번도 제대로 성공한 적이 없어서요..물론 맡으면 최선을 다하겠지만..그거 빼고는 다 괜찮을 것 같습니다..ㅠㅠ

**Comment by apple0605a** [comment]
저도 파일 부분은 어려운데...
그러면 일단 기능을 더 생각한 후에 거기서 나눠서 분업을 하는게 어떨까요?

**Comment by apple0605a** [comment]
그리고 파일 부분은 우선 제가 구현은 해볼게요
나중에 같이 확인하면서 수정해봐요

**Comment by 22100522LeeSuin** [comment]
앗 그러면 파일부분은 같이 고민해보는게 좋을 것 같아요!

**Comment by apple0605a** [comment]
그러면 기능은 뭘 추가하면 좋을까요?

**Comment by 22100522LeeSuin** [comment]
흠 20대 평균 지출을 인터넷 정보로 알아와서 지출이 그거보다 많으면 지출이 많다고 알려주는 건 어떨까요?

**Comment by apple0605a** [comment]
오 좋을 것 같아요

**Comment by 22100522LeeSuin** [comment]
평균 지출 이상일 경우 어떤 분야에서 지출이 많이 나갔는지 알려주는 것도 좋을 것 같아요

**Comment by apple0605a** [comment]
그러면 연령대별 지출 같은 자료를 수집해서 기능 구현하는데에 사용하면 될 것 같네요

**Comment by 22100522LeeSuin** [comment]
좋은 것 같습니다!

**Comment by apple0605a** [comment]
그러면 기능에
사용자 또래 지출과 사용자 지출 비교

**Comment by apple0605a** [comment]
이런 식으로 추가하고 다른 기능은 천천히 생각하고 추가해볼까요?

**Comment by 22100522LeeSuin** [comment]
지출 계획 기능을 넣어서 다음날 지출을 대략 예상해주는 기능도 괜찮을 거같아요

**Comment by 22100522LeeSuin** [comment]
앗 좋습니다!

**Comment by apple0605a** [comment]
CRUD
FILE 저장 및 수정
분야별 지출 내역 조회
총 지출 조회
사용자와 사용자 또래 지출 비교
지출 예정 기록 (지출 예측)
향후 변경 및 추가 예정

기능은 이정도로 일단 적고 여기서 분업하면 될 것 같아요

**Comment by 22100522LeeSuin** [comment]
넵! 
CRUD + 분야별 지출 내역 조회
총지출 조회 + 사용자와 또래지출 비교 + 지출 예정 기록
FILE 저장 및 수정 : 같이
이렇게 나누는 건 어떤가요? CRUD는 아무래도 연결되어 있는 거다보니까 한 사람이 맡는게 덜 혼란스럽지 않을까요?

**Comment by apple0605a** [comment]
이렇게 나누면 좋을 것 같아요
학우님은 원하시는 쪽이 있나요?

**Comment by 22100522LeeSuin** [comment]
앗 저는 둘다 상관 없습니다!

**Comment by apple0605a** [comment]
그러면 제가 CRUD랑 분야별 지출 내역 조회 부분을 맡아도 될까요?

**Comment by 22100522LeeSuin** [comment]
넵! 그럼 제가 아래거 맡겠습니다!
